[book]
title = "Kirino 문서"
description = "완전한 RBAC 지원을 갖춘 커스터마이저블 제로 트러스트 인증 프레임워크"
authors = ["celestia-island"]
language = "ko"
src = "."

[build]
build-dir = "../../target/docs/ko"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/celestia-island/kirino"
edit-url-template = "https://github.com/celestia-island/kirino/edit/dev/docs/ko/{path}"
additional-js = ["../theme/lang-switcher.js"]
additional-css = ["../theme/lang-switcher.css"]
