[book]
title = "Документация Kirino"
description = "Настраиваемый zero-trust фреймворк аутентификации с полной поддержкой RBAC"
authors = ["celestia-island"]
language = "ru"
src = "."

[build]
build-dir = "../../target/docs/ru"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/celestia-island/kirino"
edit-url-template = "https://github.com/celestia-island/kirino/edit/dev/docs/ru/{path}"
additional-js = ["../theme/lang-switcher.js"]
additional-css = ["../theme/lang-switcher.css"]
