[book]
title = "Kirino Documentation"
description = "A customizable, zero-trust authentication framework with full RBAC support"
authors = ["celestia-island"]
language = "en"
src = "."

[build]
build-dir = "../../target/docs/en"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/celestia-island/kirino"
edit-url-template = "https://github.com/celestia-island/kirino/edit/dev/docs/en/{path}"
additional-js = ["../theme/lang-switcher.js"]
additional-css = ["../theme/lang-switcher.css"]
