[site]
title = "Kirino"
description = "A customizable, zero-trust authentication and authorization framework with RBAC and dynamic risk assessment."

cname = "kirino.docs.celestia.world"
[languages]
default = "en"
order = ["en", "zhs", "zht", "ja", "ko", "fr", "es", "ru", "ar"]
