[book]
title = "Documentation Kirino"
description = "Un framework d'authentification zero-trust personnalisable avec support RBAC complet"
authors = ["celestia-island"]
language = "fr"
src = "."

[build]
build-dir = "../../target/docs/fr"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/celestia-island/kirino"
edit-url-template = "https://github.com/celestia-island/kirino/edit/dev/docs/fr/{path}"
additional-js = ["../theme/lang-switcher.js"]
additional-css = ["../theme/lang-switcher.css"]
