name: Publish crates.io

on:
  push:
    tags: [v*]

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo check -p kirino-session -p kirino -p kirino-macro --lib
      - name: Install celestia-devtools
        run: pip install git+https://github.com/celestia-island/celestia-devtools.git
      - run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - run: python -m celestia_devtools.publish.crates
